### PR TITLE
Mark infrequently used functions as cold rather than manually putting…

### PR DESCRIPTION
**Pull request by glandium**
… them in a separate section

### CODE REVIEW

**Comment by glandium** [comment]
Unintuitively, this helps fix https://bugzilla.mozilla.org/show_bug.cgi?id=1742972

**Comment by glandium** [comment]
(I had marked as draft for a couple hours because I had issues which turned out to be sccache vs. rust issue 58393)

**Comment by ncalexan** [comment]
Might as well try it; the proof will be in the pudding.  It's not clear where the conditions for GCC and clang versions are coming from.  They're not the same as `MOZ_COLD` in m-c, and I can't easily see documentation with those details.  Can you comment here or on the BZ ticket where those come from?

**Comment by glandium** [comment]
They are the versions of clang and gcc that added support for the attribute. MOZ_COLD doesn't care about the exact versions because the minimum version of gcc and clang supported in Gecko already support the attribute.

**Pull request merged**
